// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  angular.module("angularGenApp").directive("bblAssetify", function() {
    var postLink;

    return {
      template: "<div></div>",
      restrict: "E",
      link: postLink = function(scope, element, attrs) {
        return element.text("this is the bblAssetify directive");
      }
    };
  });

}).call(this);
