// Generated by CoffeeScript 1.6.2
(function() {
  this.appModule = angular.module("appModule", [], function($routeProvider, $locationProvider) {
    return $routeProvider.when("/", {
      templateUrl: "templates/index.html"
    });
  });

  this.AppCntl = function($scope, $log, userDataSource, runtime) {
    $scope.addSticker = function(sticker) {
      $scope.page.addSticker(sticker);
      return userDataSource.persist($scope.page);
    };
    $scope.page = new Page();
    runtime.withCurrentResource(function(url) {
      return $scope.page.url = url;
    });
    return userDataSource.fetch('stickers', [], function(stickers) {
      $scope.stickers = stickers;
      $log.info(JSON.stringify($scope.stickers));
      return $scope.$apply();
    });
  };

  this.Page = Parse.Object.extend("Page", {
    url: 'stub-url',
    addSticker: function(sticker) {
      var _base;

      if (!this.stickers) {
        this.stickers = [];
      }
      if (!(typeof (_base = this.stickers).include === "function" ? _base.include(sticker) : void 0)) {
        this.stickers.push(sticker);
      }
      return console.log({
        obj: this,
        msg: "stickers: " + this.stickers
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=popup.map
*/
