// Generated by CoffeeScript 1.6.2
(function() {
  if (chrome.webRequest) {
    chrome.webRequest.onHeadersReceived.addListener((function(info) {
      var header, headers, i;

      headers = info.responseHeaders;
      i = headers.length - 1;
      while (i >= 0) {
        header = headers[i].name.toLowerCase();
        if (header === "x-frame-options" || header === "frame-options") {
          headers.splice(i, 1);
        }
        --i;
      }
      return {
        responseHeaders: headers
      };
    }), {
      urls: ["*://*/*"],
      types: ["main_frame", "sub_frame"]
    }, ["blocking", "responseHeaders"]);
  } else {
    console.warn("couldn't find chrome.webRequest - OAuth will not work inside a frame!");
  }

}).call(this);
