// Generated by CoffeeScript 1.6.2
(function() {
  this.appModule.factory('runtime', function($log) {
    return {
      withCurrentResource: function(callback) {
        var url,
          _this = this;

        if (chrome.extension) {
          $log.info("initializing chrome extension environment");
          return chrome.tabs.query({
            active: true
          }, function(tabs) {
            var url;

            url = tabs[0].url;
            $log.info({
              page: _this,
              url: url
            });
            return callback(url);
          });
        } else {
          $log.info("not running as chrome extension");
          url = 'out-of-chrome-stub-url';
          return callback(url);
        }
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=runtime.map
*/
