// Generated by CoffeeScript 1.6.2
(function() {
  this.appModule.factory('runtime', function($log) {
    return {
      withCurrentResource: function(callback) {
        var url;

        if (chrome.extension) {
          $log.info("initializing chrome extension environment");
          return chrome.windows.getCurrent({}, function(chromeWindow) {
            var _this = this;

            return chrome.tabs.query({
              windowId: chromeWindow.id,
              active: true
            }, function(tabs) {
              var url;

              $log.info(tabs);
              url = tabs[0].url;
              $log.info({
                msg: "chrome env",
                url: url
              });
              return callback(url);
            });
          });
        } else {
          $log.info("not running as chrome extension");
          url = 'out-of-chrome-stub-url';
          return callback(url);
        }
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=runtime.map
*/
