// Generated by CoffeeScript 1.6.2
(function() {
  this.appModule = angular.module("appModule", [], function($routeProvider, $locationProvider) {
    return $routeProvider.when("/", {
      templateUrl: "templates/index.html"
    });
  });

  Parse.initialize("RnNIA4148ExIhwBFNB9qMGci85tOOEBHbzwxenNY", "5FSg0xa311sim8Ok1Qeob7MLPGsz3wLFQexlOOgm");

  this.AppCntl = function($scope, $log, userDataSource) {
    $scope.navigateTo = function(sticker) {
      return $scope.selectedSticker = sticker;
    };
    $scope.fetchItems = function(sticker) {
      return userDataSource.fetch('items', [sticker], function(items) {
        $log.info(items);
        sticker.items = items;
        return $scope.$apply();
      });
    };
    return userDataSource.fetchStickers(null, function(stickers) {
      $scope.stickers = stickers;
      $log.info(JSON.stringify($scope.stickers));
      if (stickers.length > 0) {
        $scope.navigateTo(stickers[0]);
      }
      return $scope.stickers.forEach(function(sticker) {
        return $scope.fetchItems(sticker);
      });
    });
  };

}).call(this);
