// Generated by CoffeeScript 1.6.2
(function() {
  var myRequire,
    __slice = [].slice;

  this.appModule = angular.module("appModule", [], function($routeProvider, $locationProvider) {});

  this.EvernoteLoginCntl = function($scope, $rootScope, $location, $log, globalsSvc, evernoteSvc) {
    var params;

    $scope.loginWithEvernote = function() {
      window.evernoteAuthenticator.initialize();
      return window.evernoteAuthenticator.loginWithEvernote();
    };
    params = $location.search();
    if (params.oauth_token && params.oauth_verifier) {
      window.evernoteAuthenticator.postAuthenticationCallback = function() {
        var redirect_url;

        localStorage.setItem('evernote_authToken', window.authTokenEvernote);
        localStorage.setItem('evernote_noteStoreURL', window.noteStoreURL);
        evernoteSvc.init();
        $rootScope.authentication.setLoggedIn();
        $log.info({
          msg: "got access token from evernote",
          svc: evernoteSvc
        });
        window.parent.evernoteSvc = evernoteSvc;
        redirect_url = localStorage.getItem("oauth_success_redirect_path");
        $log.info("redirecting parent window to " + redirect_url);
        return window.parent.location.href = redirect_url;
      };
      return evernoteAuthenticator.initialize();
    } else {
      return new Q.fcall(function() {
        var result;

        return result = $scope.loginWithEvernote();
      }).then(null, function(err) {
        return $log.error(err);
      });
    }
  };

  myRequire = function() {
    var libfiles, loads;

    libfiles = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    loads = libfiles.map(function(file) {
      return $q.promise(function() {});
    });
    return $q.all(loads);
  };

}).call(this);
