// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  angular.module("appModule").directive("bblAssetify", function() {
    var postLink;

    return {
      restrict: "A",
      link: postLink = function(scope, element, attrs) {
        var assetUrl, classVal, scrubbedText, styleText, styleVal;

        scrubbedText = element.text().toLowerCase().trim();
        assetUrl = "assets/" + scrubbedText + ".png";
        styleVal = attrs.style;
        styleText = "background-image: url(\"" + assetUrl + "\");";
        attrs.$set('style', (styleVal && styleVal + " " || "") + styleText);
        classVal = attrs["class"];
        return attrs.$set('class', (classVal && classVal + " " || "") + scrubbedText);
      }
    };
  });

}).call(this);
