// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = this.appModule;

  angular.module('appModule').controller('AuthenticationCntl', function($scope, $rootScope, $log, $location, $resource, globalsSvc, userPrefs) {
    $scope.doLogin = function() {
      var authenticationDetails;

      authenticationDetails = $resource(userPrefs.apiServer.replace(/:(\d+)/, '\\:$1') + '/authentication/details').get();
      return authenticationDetails.$then(function() {
        if (authenticationDetails) {
          app.userPrefs.authToken = authenticationDetails.authToken;
          app.userPrefs.noteStoreURL = authenticationDetails.noteStoreURL;
          $rootScope.authentication.setLoggedIn();
          return $location.path('/');
        }
      }).then(function() {
        if (app.userPrefs.authToken) {
          return;
        }
        return location.href = userPrefs.apiServer + '/authentication';
      });
    };
    if ($location.path().match(/logout/)) {
      return $rootScope.authentication.setLoggedOut();
    } else if ($location.path().match(/login$/)) {
      return $scope.doLogin();
    }
  });

}).call(this);
