// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = this.appModule;

  angular.module('appModule').controller('AuthenticationCntl', function($scope, $rootScope, $log, $location, $resource, globalsSvc, userPrefs, envs) {
    $scope.loginForm = {
      username: userPrefs.get('username')
    };
    $scope.doLogin = function() {
      var authenticationDetails, serverLoc;

      userPrefs.set('username', $scope.loginForm.username);
      globalsSvc.setupRestangular();
      serverLoc = envs[userPrefs.get('env')].apiServer;
      authenticationDetails = $resource(serverLoc.replace(/:(\d+)/, '\\:$1') + '/authentication/details').get();
      return authenticationDetails.$then(function() {
        if (authenticationDetails) {
          app.userPrefs.authToken = authenticationDetails.authToken;
          app.userPrefs.noteStoreURL = authenticationDetails.noteStoreURL;
          $rootScope.authentication.setLoggedIn();
          return $location.path('/');
        }
      }).then(function() {
        if (app.userPrefs.authToken) {
          return;
        }
        return location.href = serverLoc + '/authentication';
      });
    };
    if ($location.path().match(/logout/)) {
      return $rootScope.authentication.setLoggedOut();
    } else if ($location.path().match(/login$/)) {
      return console.log('login requested.');
    }
  });

}).call(this);
