// Generated by CoffeeScript 1.6.2
(function() {
  var that;

  that = this;

  this.appModule.factory('stubDataSvc', function($log, $http, $resource) {
    var obj;

    obj = {
      init: function() {},
      fetchPage: function(params) {
        var deferred, results;

        deferred = Q.defer();
        results = $resource('http://localhost\\:8081/mackerel/page').get(params, function() {
          return deferred.resolve(results);
        });
        return deferred.promise;
      },
      fetchStickers: function(page) {
        var deferred, results;

        deferred = Q.defer();
        results = $resource('http://localhost\\:8081/mackerel/tags').query(function() {
          results = results.map(function(e) {
            return new that.Sticker(e);
          });
          return deferred.resolve(results);
        });
        return deferred.promise;
      },
      updateSticker: function(sticker) {
        return Q.fcall(function() {
          $log.error("stub updateSticker called");
          return null;
        });
      },
      persist: function(type, modelObj, resultHandler) {
        return Q.fcall(function() {
          $log.error("stub persist called");
          return null;
        });
      },
      fetchItems: function(params, resultHandler) {
        return Q.fcall(function() {
          $log.error("stub fetchItems called");
          return null;
        });
      }
    };
    return obj;
  });

}).call(this);
