// Generated by CoffeeScript 1.6.2
(function() {
  var feedback;

  this.feedbackAdded = false;

  feedback = function() {
    var UserVoice, script, uv;

    if (this.feedbackAdded) {
      return;
    }
    uv = document.createElement('script');
    uv.async = 'async';
    uv.src = "https://widget.uservoice.com/akwF2Qs6Se6qr848MmMA.js";
    script = document.getElementsByTagName('script')[0];
    script.parentNode.insertBefore(uv, script);
    UserVoice = window.UserVoice || (window.UserVoice = []);
    UserVoice.push([
      'showTab', 'classic_widget', {
        mode: 'full',
        primary_color: '#cc6d00',
        link_color: '#007dbf',
        default_mode: 'feedback',
        forum_id: 191718,
        topic_id: 37728,
        support_tab_name: 'Support',
        feedback_tab_name: 'Feedback',
        tab_label: 'Talk to us!',
        tab_color: '#cc6d00',
        tab_position: 'bottom-right',
        tab_inverted: true
      }
    ]);
    return this.feedbackAdded = true;
  };

  feedback();

}).call(this);
